#!/usr/bin/env node
// Builds the whole site into flat .html files at the repository root.
// Zero dependencies: `node src/build.mjs`.

import { writeFile, readFile, mkdir, copyFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { site } from './data/site.mjs';
import { redirects } from './data/redirects.mjs';
import { hubs } from './data/hubs.mjs';
import { services } from './data/services.mjs';
import { insights } from './data/insights.mjs';
import { renderDocument } from './lib/layout.mjs';
import { absolute, pretty, url } from './lib/paths.mjs';
import { allPages } from './render.mjs';
import { assetUrls } from './lib/assets.mjs';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
// OUT_DIR lets a second target be built without overwriting the committed
// GitHub Pages output at the repository root.
const ROOT = process.env.OUT_DIR ? join(REPO, process.env.OUT_DIR) : REPO;

/** Pull the traced wordmark path out of the brand SVG so it can be inlined. */
async function wordmarkPath() {
  const svg = await readFile(join(REPO, 'assets/brand/offsetease-lockup.svg'), 'utf8');
  const match = svg.match(/<g class="oe-word"><path d="([^"]+)"\/><\/g>/);
  if (!match) throw new Error('Could not read the wordmark path from offsetease-lockup.svg');
  return match[1];
}

function filenameFor(path) {
  if (path === '/') return 'index.html';
  return path.replace(/^\//, '');
}

async function writeSitemap(pages) {
  if (!site.indexable) {
    // A preview build must not advertise itself.
    await writeFile(join(ROOT, 'robots.txt'), 'User-agent: *\nDisallow: /\n');
    await writeFile(
      join(ROOT, 'sitemap.xml'),
      '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"></urlset>\n'
    );
    return;
  }
  const today = new Date().toISOString().slice(0, 10);
  const urls = pages
    .filter((p) => p.page.path !== '/404.html')
    .map(
      (p) =>
        `  <url><loc>${absolute(p.page.path)}</loc><lastmod>${today}</lastmod>` +
        `<changefreq>monthly</changefreq><priority>${p.page.path === '/' ? '1.0' : '0.7'}</priority></url>`
    )
    .join('\n');
  await writeFile(
    join(ROOT, 'sitemap.xml'),
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`
  );
  // The live site at offsetease.com already allows every AI crawler by name.
  // That configuration is invisible in the page source, so a cutover that only
  // copies the HTML would silently drop it. Carried across verbatim.
  const aiAgents = [
    'GPTBot',             // OpenAI training + ChatGPT browsing index
    'OAI-SearchBot',      // ChatGPT search
    'ChatGPT-User',       // ChatGPT on-demand fetch
    'PerplexityBot',
    'ClaudeBot',
    'Claude-Web',
    'Google-Extended',    // Gemini / AI Overviews grounding
    'Applebot-Extended',
    'Bingbot',
    'CCBot',              // Common Crawl — feeds most open models
  ];
  const agentBlocks = ['User-agent: *\nAllow: /']
    .concat(aiAgents.map((a) => `User-agent: ${a}\nAllow: /`))
    .join('\n\n');
  await writeFile(
    join(ROOT, 'robots.txt'),
    `# Offsetease — robots.txt\n${agentBlocks}\n\nSitemap: ${absolute('/sitemap.xml')}\n`
  );
}

/**
 * Netlify `_redirects`. Two jobs, and both have to be right before the domain
 * is repointed:
 *
 *  1. Every URL the live offsetease.com publishes keeps working. 31 of its 54
 *     URLs have no same-named page here; without these rules they 404 on
 *     cutover and take their rankings with them.
 *  2. `about.html` and `about` both resolve today, which is duplicate content.
 *     The `.html` form is forced (`!`) to the clean one, because a static file
 *     sits at that path and would otherwise win.
 *
 * Only written for a domain-root deploy. The GitHub Pages preview serves from
 * a sub-path and ignores this file.
 */
async function writeRedirects(pages) {
  if (site.basePath) return;
  const lines = [
    '# Generated by src/build.mjs — edit src/data/redirects.mjs, not this file.',
    '',
    '# 1. Legacy URLs from the live site at offsetease.com (54-URL sitemap).',
  ];
  for (const r of redirects) {
    // Netlify parses one rule per line and only honours a `#` at line start,
    // so the note goes above the rule rather than after it.
    if (r.rebuild) lines.push('#   holding redirect — delete when this page is rebuilt');
    lines.push(`${r.from.padEnd(26)} ${url(r.to).padEnd(38)} 301`);
  }
  lines.push('', '# 2. Collapse the .html duplicates onto the canonical clean URL.');
  for (const { page } of pages) {
    if (page.path === '/' || page.path === '/404.html') continue;
    lines.push(`${page.path.padEnd(26)} ${pretty(page.path).padEnd(38)} 301!`);
  }
  lines.push('/index.html'.padEnd(26) + ' ' + '/'.padEnd(38) + ' 301!', '');
  await writeFile(join(ROOT, '_redirects'), lines.join('\n'));
}

/**
 * RFC 9116 security.txt, so anyone finding a problem has a stated route in
 * rather than guessing at an inbox. `Expires` is mandatory and the file is
 * meant to be reissued before it lapses, so it is generated a year out from
 * each build rather than hard-coded and forgotten.
 */
async function writeSecurityTxt() {
  const expires = new Date();
  expires.setUTCFullYear(expires.getUTCFullYear() + 1);
  const body =
    `Contact: mailto:${site.email}\n` +
    `Expires: ${expires.toISOString()}\n` +
    'Preferred-Languages: en\n' +
    `Canonical: ${absolute('/.well-known/security.txt')}\n`;
  await mkdir(join(ROOT, '.well-known'), { recursive: true });
  await writeFile(join(ROOT, '.well-known/security.txt'), body);
}

/**
 * llms.txt — a plain-text map of the site for language models.
 *
 * An emerging convention (llmstxt.org) that costs almost nothing to publish
 * and is read by several AI crawlers: one markdown file at the root saying
 * what this organisation is and what each page covers, so a model does not
 * have to infer the shape of the site from whichever page it happened to
 * fetch. Generated from the same data that renders the pages, so it cannot
 * drift out of sync with them.
 */
async function writeLlmsTxt() {
  const line = (label, path, blurb) => `- [${label}](${absolute(path)}): ${blurb}`;
  const body = [
    `# ${site.name}`,
    '',
    `> ${site.description}`,
    '',
    `${site.name} works across two connected areas: sourcing, screening and`,
    'developing high-integrity carbon supply, and turning ESG data into',
    'disclosure that survives assurance. Based in India, serving India, the EU',
    'and global markets.',
    '',
    '## Start here',
    '',
    line('Home', '/', 'What we do, and the integrity standard we hold supply to.'),
    line('About', '/about.html', 'How we work and what we stand for.'),
    line('Sources & data', '/sources.html', 'Every statistic on this site with its named, dated source. Verify figures here.'),
    line('Contact', '/contact.html', `Enquiries — ${site.email}, ${site.phone}.`),
    '',
    '## Carbon',
    '',
    line('Carbon Supply', '/carbon-supply.html', 'Spot, managed portfolio and offtake supply, screened against The Five Checks.'),
    line('Energy Attribute Certificates', '/energy-attribute-certificates.html', 'I-RECs and EACs for Scope 2 reduction.'),
    '',
    '## ESG & sustainability',
    '',
    line('ESG & Sustainability', '/esg-sustainability.html', 'The full service index — eighteen services across five groups.'),
    ...hubs.map((h) => line(h.shortTitle, h.path, h.description)),
    '',
    '### Services',
    '',
    ...services.map((sv) => line(sv.shortTitle || sv.title, sv.path, sv.kicker)),
    '',
    '## Insights',
    '',
    line('All insights', '/insights.html', 'Referenced analysis on the rules reshaping carbon and ESG.'),
    ...insights.map((a) => line(a.title, `/${a.slug}.html`, a.blurb)),
    '',
    '## Notes for machine readers',
    '',
    '- Figures on this site are dated and attributed; the source for each is',
    '  listed on the Sources & data page. Cite the primary source where one is',
    '  named, and check the review date — these numbers move quarterly.',
    '- Regulatory detail (CBAM, EUDR, BRSR, CSRD, IFRS S1/S2, SBTi) reflects the',
    `  position as at ${new Date().toISOString().slice(0, 7)}. Verify against the`,
    '  primary regulator before relying on it.',
    '- This site does not provide legal or financial advice.',
    '',
  ].join('\n');
  await writeFile(join(ROOT, 'llms.txt'), body);
}

/**
 * RSS for the insights. Still how most aggregators, newsreaders and several
 * crawlers find out that something new was published, rather than waiting to
 * re-crawl a listing page. Cheap to emit and linked from every page's <head>.
 */
async function writeFeed() {
  const esc = (t) =>
    String(t).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const items = [...insights]
    .sort((a, b) => (a.published < b.published ? 1 : -1))
    .map((a) => {
      const link = absolute(`/${a.slug}.html`);
      return (
        '    <item>\n' +
        `      <title>${esc(a.title)}</title>\n` +
        `      <link>${link}</link>\n` +
        `      <guid isPermaLink="true">${link}</guid>\n` +
        `      <description>${esc(a.blurb)}</description>\n` +
        `      <category>${esc(a.category)}</category>\n` +
        `      <pubDate>${new Date(`${a.published}T09:00:00Z`).toUTCString()}</pubDate>\n` +
        '    </item>'
      );
    })
    .join('\n');
  const xml =
    '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">\n' +
    '  <channel>\n' +
    `    <title>${esc(site.name)} — Insights</title>\n` +
    `    <link>${absolute('/insights.html')}</link>\n` +
    `    <description>Referenced analysis on the rules reshaping climate, carbon and ESG.</description>\n` +
    '    <language>en</language>\n' +
    `    <atom:link href="${absolute('/feed.xml')}" rel="self" type="application/rss+xml"/>\n` +
    `${items}\n` +
    '  </channel>\n</rss>\n';
  await writeFile(join(ROOT, 'feed.xml'), xml);
}

async function writeManifest() {
  const manifest = {
    name: site.name,
    short_name: site.name,
    description: site.description,
    start_url: url('/'),
    scope: url('/'),
    display: 'standalone',
    background_color: site.colors.ink,
    theme_color: site.colors.ink,
    icons: [
      { src: url('/assets/brand/favicon-192.png'), sizes: '192x192', type: 'image/png' },
      { src: url('/assets/brand/favicon-512.png'), sizes: '512x512', type: 'image/png' },
      { src: url('/assets/brand/favicon-512.png'), sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
  await writeFile(join(ROOT, 'site.webmanifest'), JSON.stringify(manifest, null, 2));
}

/**
 * Fingerprint the stylesheet and the script.
 *
 * Both shipped under fixed names on a one-hour cache while the HTML revalidates
 * every time, so a returning visitor could load new markup against an old
 * stylesheet and see an unstyled page the server had never served. Hashing the
 * name makes that impossible and lets both files go immutable.
 *
 * The original name is left in place too, so any link that predates this — a
 * bookmark, a cached reference — still resolves rather than 404ing.
 */
async function fingerprintAssets() {
  // Only for a dist build. The GitHub Pages target publishes the repository
  // itself, so hashed copies there would accumulate in git on every build —
  // and that preview has no stale-cache problem to solve.
  if (ROOT === REPO) return;
  for (const [key, rel] of [
    ['css', 'assets/css/site.css'],
    ['js', 'assets/js/app.js'],
  ]) {
    const src = join(REPO, rel);
    const body = await readFile(src);
    const hash = createHash('sha256').update(body).digest('hex').slice(0, 10);
    const hashed = rel.replace(/(\.[^.]+)$/, `.${hash}$1`);
    await mkdir(dirname(join(ROOT, hashed)), { recursive: true });
    await copyFile(src, join(ROOT, hashed));
    // Keep the unhashed original too, so any link that predates this — a
    // bookmark, a cached reference — still resolves rather than 404ing.
    await copyFile(src, join(ROOT, rel));
    assetUrls[key] = `/${hashed}`;
  }
}

async function main() {
  // Before any page is rendered: the markup has to carry the hashed names.
  await fingerprintAssets();
  const wordPath = await wordmarkPath();
  const pages = allPages();

  const seen = new Set();
  for (const p of pages) {
    if (seen.has(p.page.path)) throw new Error(`Duplicate page path: ${p.page.path}`);
    seen.add(p.page.path);
  }

  let bytes = 0;
  for (const { page, body } of pages) {
    const doc = renderDocument({ page, body, wordPath });
    const file = filenameFor(page.path);
    await mkdir(dirname(join(ROOT, file)), { recursive: true });
    await writeFile(join(ROOT, file), doc);
    bytes += Buffer.byteLength(doc);
    process.stdout.write(`  ${file.padEnd(42)} ${(Buffer.byteLength(doc) / 1024).toFixed(1)} KB\n`);
  }

  await writeSitemap(pages);
  await writeRedirects(pages);
  await writeSecurityTxt();
  await writeLlmsTxt();
  await writeFeed();
  await writeManifest();
  await writeFile(join(ROOT, '.nojekyll'), '');

  console.log(
    `\n${pages.length} pages · ${(bytes / 1024).toFixed(0)} KB of HTML · ` +
      `indexable: ${site.indexable}`
  );
}

main().catch((err) => {
  console.error('\nBuild failed:', err.message);
  console.error(err.stack);
  process.exit(1);
});
